force-app/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <label>Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Application__c/fields/Loan_Amount__c.field-meta.xml
<CustomField>
    <fullName>Loan_Amount__c</fullName>
    <label>Loan Amount</label>
    <precision>6</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Loan_Period__c.field-meta.xml
<CustomField>
    <fullName>Loan_Period__c</fullName>
    <label>Loan Period</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Salary__c.field-meta.xml
<CustomField>
    <fullName>Salary__c</fullName>
    <label>Salary</label>
    <precision>9</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Submitted</fullName>
                <default>true</default>
                <label>Submitted</label>
            </value>
            <value>
                <fullName>Referred</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TestReferredApplicationsController.cls
@isTest
public class TestReferredApplicationsController {
	@isTest
    static void testGetApplications_NoReferredApplications() {
        List<Application__c> applicationsList = ReferredApplicationsController.getApplications();
        System.debug('Running test');
        System.assert(applicationsList.size() == 0);
    }
    
    @isTest
    static void testGetApplications_ReferredApplicationsFound() {
        Application__c application1 = new Application__c();
        application1.Loan_Amount__c = 2800;
        application1.Loan_Period__c = 8;
        application1.Salary__c = 20000;
        Application__c savedApp1 = ApplicationsController.saveApplication(application1);
        
        Application__c application2 = new Application__c();
        application2.Loan_Amount__c = 3000;
        application2.Loan_Period__c = 10;
        application2.Salary__c = 40000;
        Application__c savedApp2 = ApplicationsController.saveApplication(application2);
        
        List<Application__c> applicationsList = ReferredApplicationsController.getApplications();
        System.assert(applicationsList.size() == 2);
    }
    
    @isTest
    static void testSaveApplication() {
        Application__c application1 = new Application__c();
        application1.Loan_Amount__c = 2800;
        application1.Loan_Period__c = 8;
        application1.Salary__c = 20000;
        Application__c savedApp1 = ApplicationsController.saveApplication(application1);
        
        List<Application__c> applicationsList = ReferredApplicationsController.getApplications();
        System.assert(applicationsList.size() == 1);
        Application__c application = applicationsList[0];
        application.Status__c = 'Approved';
        ReferredApplicationsController.saveApplication(application);
        
        applicationsList = ReferredApplicationsController.getApplications();
        System.assert(applicationsList.size() == 0);
        
    }
}